coverage:
  ignore:
    - "builtin"
    - "ast"
    - "test"
    - "scanner"
    - "format"
    - "demo"
    - "demo/unit-test"
    - "doc/spec"
    - "cmd"
    - "cl/cltest"
    - "cl/outline"
    - "cl/internal/llgo-hello"
    - "cl/internal/mcp"
    - "cl/internal/overload"
    - "cl/internal/spx"
    - "cl/internal/spx2"
    - "cl/internal/spx3"
    - "cl/internal/test"
    - "cl/internal/unit"
    - "parser/fsx"
    - "parser/parsertest"
    - "x/jsonrpc2"
    - "x/jsonrpc2/jsonrpc2test"
    - "x/watcher"
    - "x/langserver"
    - "x/fsnotify"
    - "x/fakenet"
    - "x/typesutil"
    - "x/gocmd"
    - "x/gopenv"
    - "tool"
    - "tpl"
  