language: go
go:
  - "1.14"
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golangci/gocyclo/cmd/gocyclo
  - sudo pip --quiet install pre-commit
script:
  - export GO111MODULE="on"
  - go install -v ./...
  # check: results of go+ and go
  - gop go -test ./exec/golang/testdata
  # check: format gop file
  - find ./ -type f -name "*.gop"|xargs -n 1 gop fmt -w
  # check: imported go package
  # - diff -b  <(cat lib/default.go|grep github) <(find lib -type d|grep -v "lib$"|xargs -n 1 -I file bash -c 'echo -e \\t_ \"github.com/goplus/gop/file\"'|sort)
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - pre-commit run --all
after_success:
  - bash <(curl -s https://codecov.io/bash)
