name: Feature request
description: Propose a change to Go+

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Make sure to browse the opened and closed issues before submit your issue.

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Write your feature request in the form of a proposal to be considered for implementation.
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Describe the background problem or need that led to this feature request.
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Are there any current workarounds that you're using that others in similar positions should know about?
    validations:
      required: true
